---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ausceimj/public_html/phptest
    - export REPOSITORY=git@github.com:hiilisuunnitelma/phptest.git
    - export BRANCH=main
    - /bin/cp index.php $DEPLOYPATH